name: Internal Testing - Android Preview Build and Submit IOS Production Build

on:
  workflow_dispatch: {}

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      profile: production
      build_id: ${{ needs.build-ios.outputs.build_id }}
